name: atom
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: A hackable text editor for the 21st Century.
description: |
  Atom is a free and open source text editor that is modern,
  approachable, and hackable to the core.

grade: stable
confinement: classic

parts:
  atom:
    install: |
      DEB_API="https://atom.io/download/deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f4)
      echo $VERSION > $SNAPCRAFT_STAGE/version
    plugin: dump
    source: https://atom.io/download/deb
    source-type: deb
    # Correct path to icon.
    prepare: |
      sed -i 's|Icon=atom|/snap/atom/current/usr/share/pixmaps/atom\.png|g' usr/share/applications/atom.desktop
      sed -i 's|Exec=.*|Exec=/snap/bin/atom %F|g' usr/share/applications/atom.desktop
    after:
      - desktop-gtk2
    build-packages:
      - curl
    stage-packages:
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
  launcher:
    plugin: dump
    source: files/

apps:
  atom:
    command: bin/launcher ${SNAP}/usr/share/atom/atom
    desktop: usr/share/applications/atom.desktop
  apm:
    command: bin/launcher ${SNAP}/usr/bin/apm
